% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrartcl}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{5}
% Make \paragraph and \subparagraph free-standing
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi


\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother

\KOMAoption{captions}{tableheading}
\makeatletter
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\makeatletter
\@ifpackageloaded{tcolorbox}{}{\usepackage[skins,breakable]{tcolorbox}}
\makeatother
\makeatletter
\@ifundefined{shadecolor}{\definecolor{shadecolor}{rgb}{.97, .97, .97}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\makeatother
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Feature Engineering and Conformal Prediction in Fish Classification.},
  pdfauthor={Mariana Garcia Mejia},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}

\title{Feature Engineering and Conformal Prediction in Fish
Classification.\thanks{Code and data are available at:
\url{https://github.com/mejiama16/Fish-Project}. The data for this paper
was retrieved from the
\href{https://github.com/WidebandPingFest/FishTetherExperiment}{Fish
Tether Experiment GitHub Repository}.}}
\author{Mariana Garcia Mejia}
\date{September 30, 2026}

\begin{document}
\maketitle
\begin{abstract}
Description of methods and main findings
\end{abstract}
\ifdefined\Shaded\renewenvironment{Shaded}{\begin{tcolorbox}[boxrule=0pt, sharp corners, breakable, enhanced, frame hidden, interior hidden, borderline west={3pt}{0pt}{shadecolor}]}{\end{tcolorbox}}\fi

\hypertarget{sec-introduction}{%
\section{Introduction}\label{sec-introduction}}

Hydroacoustic signals provide a non-lethal approach for fish
classification. However, the features used for classification are
high-dimensional and highly correlated. We are also often only given
labels for a subset of the data, and must leverage both labelled and
non-labelled data to improve classification accuracy. Lastly, we often
care to understand which signals are most important for classification,
but the correlation among features distorts this signal. The student
will use various data science and machine learning approaches to address
the data structure challenges and classification tasks.

\hypertarget{sec-data}{%
\section{Data}\label{sec-data}}

\begin{verbatim}
corrplot 0.95 loaded
\end{verbatim}

\includegraphics{paper_files/figure-pdf/unnamed-chunk-3-1.pdf}

The data set contains 14,575 rows and 484 columns. Each row represents
one fish and it's measurement for a single ``ping''. A ``ping'' refers
to a time the fish hydroacoustic signal was measured and stored in the
dataset. Since multiple signals were recorded for a single fish, there
are several rows corresponding the same fish (e.g.~there are multiple
rows for LT001; Lake Trout fish number one, because multiple measures
were taken for this single fish). From now on, we call rows ``pings'',
to familiarize ourselves with how the data was being collected.

The dataset contains information for three fish species: Lake Trout
(LT), Lake Whitefish (LW) and Smallmouth Bass (SMB).
Table~\ref{tbl-data-overview} summarizes relevant information about the
dataset for each of the species.

\hypertarget{tbl-data-overview}{}
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1067}}
  >{\centering\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.2133}}
  >{\centering\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1733}}
  >{\centering\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1867}}
  >{\centering\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1600}}
  >{\centering\arraybackslash}p{(\columnwidth - 10\tabcolsep) * \real{0.1600}}@{}}
\caption{\label{tbl-data-overview}Overview of the
dataset}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Species
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Number of fish
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Total pings
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median pings
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Min. pings
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Max. pings
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Species
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Number of fish
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Total pings
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Median pings
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Min. pings
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Max. pings
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
LT & 21 & 7,248 & 213 & 16 & 1,379 \\
LW & 11 & 4,285 & 310 & 33 & 1,619 \\
SMB & 12 & 3,042 & 210 & 14 & 1,071 \\
\end{longtable}

The data was obtained from 44 distinct fishes: 21 Lake Trout, 11 Lake
Whitefish and and 12 Smallmouth Bass. Lake Trout fishes has more pings
(instances where data was collected from them), followed by Lake
Whitefish and Smallmouth Bass. Although the LW species had less
individual fish, more pings were obtained for this species than for SMB.
The median pings column shows the median number of pings across all
individual fishes for a certain species, in other words, what was the
median number of instances where measurements were taken from a single
fish. The values are fairly similar across LT and SMB, while LW had more
pings in a single fish compared to the other. This is likely because the
minimum and maximum number of pings obtained for LW is much higher than
for LT and SMB.

It is important to understand the structure of the data and how it is
collected, as it largely shapes the statistical method we select and how
we make decisions throughout the process. In particular, the rows in
this data do not represent single instances or observations, rather,
each represents an instance of a subject in time; a measurement taken
from a fish. As a result, it is possible for measurements obtained in
this instances, although different may be highly correlated, as they
come from a similar procedure done on a same subject multiple times. For
instance, the rows 1-65 in the raw data set correspond to LT001, Lake
Trout fish number one. Because all hydroacoustic signals are taken from
this single fish, just at different points in time, it is possible for
these to vary very little from measurement to measurement, resulting in
highly correlated variables.

Now, one might think that the solution is to constraint our data set and
analysis to just the 44 individual fish, by randomly selecting one of
the measurements taken from each of them. The first issue with this
approach is the resulting sample size. We have over 14,000 measurements
obtained from this experiment, it seems like exploring the data to
overcome the high correlation issue would be a much better solution, as
compared to blindly throwing observations away. Another issue with this
is: how do we pick which individual pings to keep and which to ignore?
Do we hand-pick them? Do we select them randomly? Do we select two per
day and ignore the rest? Lastly, when building machine learning models
with this data, how can we ensure there is no data leakage? If we keep
some observations from fish LT001 in the training set and some in the
testing set, it is possible that due to the high correlation between
these, the model has already memorized these patterns, leading to an
overestimation of the model's actual capacity.

This paper will touch on some of the decisions we must make when
building models using this kind of data, and compare across them. We
will do so in the context of feature engineering: deciding which
features or variables are the most informative in the classification
task. That is, given all the signals we have available for a new,
unknown fish, which of these signals are the most likely to help us
decide whether this fish is a Lake Trout, a Lake Whitefish or a
Smallmouth Bass.

\hypertarget{exploratory-data-analysis}{%
\subsection{Exploratory data analysis}\label{exploratory-data-analysis}}

Before jumping into the methods by which we will perform feature
engineering. It is important to better understand other characteristics
of the data. First, the data contains a time series component. The pings
for each fish at taken at different times throughout a period of time,
no two pings happen simultaneously. Hence, it is of interest to also
understand this characteristic of our data that may also shape our
upcoming decisions.

\hypertarget{tbl-data-time}{}
\begin{longtable}[]{@{}lcc@{}}
\caption{\label{tbl-data-time}Span of the data collection process
(pings)}\tabularnewline
\toprule\noalign{}
Species & Earliest day a ping was made & Latest day a ping was made \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Species & Earliest day a ping was made & Latest day a ping was made \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
LT & 2022-07-21 & 2022-07-28 \\
LW & 2022-07-23 & 2022-07-28 \\
SMB & 2022-07-26 & 2022-07-28 \\
\end{longtable}

Table~\ref{tbl-data-time} shows that the data was collected in the span
of a week, with SMB having data collected in a much shorter period of
time. Note that the data set included other dates, for example
\texttt{processedDate}, however we keep \texttt{sampleDate} to reflect
the time the measurement was taken.

As mentioned earlier, the data set contains a total of 484 columns, out
of which \textbf{426 are hydro acoustic signals} or frequencies. The
rest contains species, unique identifier for the fish and other
variables like sex, air bladder weight, tissue sample, length, among
others. It is possible that these measures where taken via more
aggressive methods, as a result, our analysis focuses on just the hydro
acoustic signals, as a form to explore non-lethal methods to deal with
species classification and problems adjacent to it.

These values range from roughly -20 to -105, they particularly appear as
negative.

\hypertarget{analysis-of-one-species-lake-trout}{%
\subsection{Analysis of one species: Lake
Trout}\label{analysis-of-one-species-lake-trout}}

In this following section, we explore the different variables available
in the data set for the Lake Trout species.

\begin{table}

\caption{\textbf{?(caption)}}\begin{minipage}[t]{\linewidth}

{\centering 

\raisebox{-\height}{

\includegraphics{paper_files/figure-pdf/tbl-frequency-variation-1.pdf}

}

}

\end{minipage}%

\end{table}

\textbf{?@tbl-frequency-variation} demonstrates significant variation in
signals F45, F55, F65 across different pings for the same fish, LT001.
However, it is difficult to see how the time component is present.

\includegraphics{paper_files/figure-pdf/unnamed-chunk-7-1.pdf}

\includegraphics{paper_files/figure-pdf/unnamed-chunk-8-1.pdf}

\includegraphics{paper_files/figure-pdf/unnamed-chunk-9-1.pdf}

\begin{verbatim}
# A tibble: 2 x 2
  n_missing common_missing
      <dbl>          <int>
1       183            175
2      4059            161
\end{verbatim}

Missing values: 161 frequencies are missing for 4,059 pings/rows and 175
frequencies are missing for 183 pings/rows. Since the information is
missing just for some observations rather than for entire columns,
dropping them could mean losing information. From F173-F260 there are
183 missing for each and from F90-F170 we are missing 4059 for each.

\begin{verbatim}
# A tibble: 336 x 3
   col   n_missing pct_missing
   <chr>     <dbl>       <dbl>
 1 F90        4059        27.8
 2 F90.5      4059        27.8
 3 F91        4059        27.8
 4 F91.5      4059        27.8
 5 F92        4059        27.8
 6 F92.5      4059        27.8
 7 F93        4059        27.8
 8 F93.5      4059        27.8
 9 F94        4059        27.8
10 F94.5      4059        27.8
# i 326 more rows
\end{verbatim}

\includegraphics{paper_files/figure-pdf/unnamed-chunk-12-1.pdf}

\begin{verbatim}
# A tibble: 3 x 3
  species        `F173–F260` `F90–F170`
  <chr>                <int>      <int>
1 lakeTrout            32025     477204
2 lakeWhitefish            0     127029
3 smallmouthBass           0      49266
\end{verbatim}

\hypertarget{methods}{%
\section{Methods}\label{methods}}

\hypertarget{variance-filtering}{%
\subsection{Variance filtering}\label{variance-filtering}}

\includegraphics{paper_files/figure-pdf/unnamed-chunk-14-1.pdf}

\hypertarget{pca}{%
\subsection{PCA}\label{pca}}

Before doing PCA. Questions: 1. What to do about missing values? Missing
for some fish, not for others. 2. I don't think using all 14,000 will be
too informative. Should we average all the variables for a single fish?
I'm not sure how to use this.

\hypertarget{results}{%
\section{Results}\label{results}}

\hypertarget{discussion}{%
\section{Discussion}\label{discussion}}



\end{document}
